REDVM-495: updating docs for leaf cert rotations.
pivotal-cf/docs-redis pull request #545
Opened 2024-07-10 10:04 UTC by ashrivastav13

Added step is workaround to trust newly generated certificate adding it to bosh trusted text box section.

# Pull request template

Which other branches should this be merged with (if any)?

2024-07-11 16:35 UTC, pnikonowicz requested changes
further discussion needed in regards to workaround. redis shouldn't have any special steps with it's rotation procedure as far as i know.

2024-07-11 16:35 UTC, pnikonowicz commented on rotating-ca.html.md.erb
> +The existing versions of the Redis tile for Tanzu Application Service do not support the above [recommended certificate rotation procedure](https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/
i was unaware of this. we currently have maestro tests that verify that we can rotate certs using maestro. wouldn't this mean that we do support rotating certs using maestro?

2024-07-17 07:44 UTC, ashrivastav13 commented on rotating-ca.html.md.erb
> +The existing versions of the Redis tile for Tanzu Application Service do not support the above [recommended certificate rotation procedure](https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/
Okay, we can close this PR.

2024-07-18 13:25 UTC, pnikonowicz commented on rotating-ca.html.md.erb
> +The existing versions of the Redis tile for Tanzu Application Service do not support the above [recommended certificate rotation procedure](https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/
is this the work around for the drain script issue with HA deployments?

2024-07-18 17:26 UTC, ashrivastav13 commented on rotating-ca.html.md.erb
> +The existing versions of the Redis tile for Tanzu Application Service do not support the above [recommended certificate rotation procedure](https://docs.vmware.com/en/VMware-Tanzu-Operations-Manager/
Yes, it is workaround for drain script

2024-07-19 14:23 UTC, pnikonowicz approved these changes

2024-07-22 07:17 UTC, apurvasaraiya approved these changes

2024-07-30 16:22 UTC, merged